
CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    ref VARCHAR(1024) NOT NULL,
	mensagem text NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS logs (
    id SERIAL PRIMARY KEY,
    log JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

